<script lang="ts">
	import { getContext } from 'svelte';
	import { BREAK_EVEN_WAGE_CTX, type BreakEvenWageContext } from '$lib/types';
	import { WORKER_INFO_CTX, type WorkerInfoContext } from '$lib/types';

	import * as Card from '$lib/components/atoms/card';
	import * as Avatar from '$lib/components/atoms/avatar';
	import Badge from '$lib/components/atoms/badge/badge.svelte';

	import MdiHeart from '~icons/mdi/heart';
	import MdiPickaxe from '~icons/mdi/pickaxe';
	import MdiLightningBolt from '~icons/mdi/lightning-bolt';
	import MdiBitcoin from '~icons/mdi/bitcoin';

	interface Props {
		workers: [any];
		tax: number;
	}

	let breakEvenWage = getContext<BreakEvenWageContext>(BREAK_EVEN_WAGE_CTX);

	let workersInfos = getContext<WorkerInfoContext>(WORKER_INFO_CTX);

	let { workers, tax }: Props = $props();

	/**
	 * Aggregated worker statistics for the company dashboard.
	 * All derived values update reactively whenever the `workers` array changes.
	 *
	 * Formula reference:
	 *   dailyActions (per worker) = (energy × 2.4) / 10
	 *     → energy regenerates 10%/hr over 24h = 240% = 2.4× max, capped each hour
	 *     → each work action costs 10 energy
	 *   estimatedDailyWage = Σ [ dailyActions_i × production_i × wage_i ]
	 */

	/** Sum of all workers' maximum energy skill values. */
	const totalEnergy = $derived(workers.reduce((acc, w) => acc + w.userData.skills.energy.total, 0));

	/**
	 * Total work actions performed per day across all workers.
	 * Each worker regenerates 10%/hr of their max energy, so over 24h they
	 * recover 240% — effectively 2.4× their max. Each action costs 10 energy.
	 */
	const dailyWork = $derived(
		workers.reduce((acc, w) => acc + (w.userData.skills.energy.total * 2.4) / 10, 0)
	);

	/**
	 * Estimated total daily wage cost generated by all workers.
	 * Calculated per worker to avoid cross-multiplying independent stats:
	 *   wage_i × production_i × dailyActions_i
	 *
	 * Note: if a `productionCost` (units of production required per output item)
	 * needs to be factored in, divide production_i by that value before multiplying.
	 */
	const estimatedDailyWage = $derived(
		workers.reduce((acc, w) => {
			const dailyActions = (w.userData.skills.energy.total * 2.4) / 10;
			return acc + dailyActions * w.userData.skills.production.total * w.wage;
		}, 0)
	);

	/**
	 * Total production points generated per day across all workers.
	 * Calculated per worker to avoid cross-multiplying independent stats.
	 */
	const totalDailyProduction = $derived(
		workers.reduce((acc, w) => {
			const dailyActions = (w.userData.skills.energy.total * 2.4) / 10;
			return acc + dailyActions * w.userData.skills.production.total;
		}, 0)
	);

	/**
	 * Sync derived values into the shared `workersInfos` store whenever
	 * any of the source values change. Runs as a side effect after each update.
	 */
	$effect(() => {
		workersInfos.totalDailyProduction = totalDailyProduction;
		workersInfos.totalWages = estimatedDailyWage;
	});
</script>

<Card.Root class="col-span-2 flex h-full max-h-120 flex-col overflow-hidden xl:col-span-1">
	<!-- Header -->
	<Card.Header>
		<div class="flex items-start justify-between gap-2">
			<div>
				<Card.Title class="text-base">Workers</Card.Title>
				<Card.Description
					>{workers.length} active worker{workers.length !== 1 ? 's' : ''}</Card.Description
				>
			</div>
		</div>

		<!-- Summary stats row -->
		<div class="grid grid-cols-3 gap-2 text-center sm:grid-cols-3">
			{#each [{ label: 'Daily Production', value: totalDailyProduction.toFixed(1), hint: 'Production points/day', icon: MdiPickaxe }, { label: 'Avg. Energy', value: (totalEnergy / workers.length || 0).toFixed(0), hint: 'Average energy skill', icon: MdiLightningBolt }, { label: 'Daily Wages', value: estimatedDailyWage.toFixed(3), hint: 'Total wage cost/day', icon: MdiBitcoin }] as stat}
				<div class="rounded-md bg-muted px-2 py-1.5">
					<p class="text-xs text-muted-foreground">{stat.label}</p>
					<div class="flex items-center justify-center gap-1">
						{#if stat.icon}
							<stat.icon class="h-3.5 w-3.5" />
						{/if}
						<p class="text-sm font-semibold">{stat.value}</p>
					</div>
				</div>
			{/each}
		</div>
	</Card.Header>

	<!-- Worker list -->
	<Card.Content class="pm-4 flex flex-col gap-2 overflow-y-auto">
		{#each workers as worker (worker._id)}
			{@const breakEvenWithFidelity = breakEvenWage.getByFidelity?.(worker.fidelity)}
			{@const isOverBreakEven = worker.wage >= breakEvenWithFidelity}
			{@const taxedWage = (worker.wage - (worker.wage * tax) / 100).toFixed(3)}

			<article
				class="flex items-center gap-3 rounded-lg bg-card p-3 transition-colors hover:bg-muted/40 {isOverBreakEven
					? 'border border-destructive'
					: 'border'}"
			>
				<Avatar.Root class="size-9 shrink-0 rounded-lg">
					<Avatar.Image
						src={worker.userData.avatarUrl}
						alt={`Avatar of ${worker.userData.username}`}
						loading="lazy"
					/>
					<Avatar.Fallback class="rounded-lg text-xs">
						{worker.userData.username?.[0]?.toUpperCase() ?? 'U'}
					</Avatar.Fallback>
				</Avatar.Root>

				<div class="flex min-w-0 flex-1 flex-col gap-1.5">
					<!-- Top row: name + wage badges -->
					<div class="flex flex-wrap items-center justify-between gap-1">
						<h3 class="truncate text-sm font-semibold">
							{worker.userData.username}
						</h3>
						<div class="flex shrink-0 gap-1">
							<Badge
								variant={isOverBreakEven ? 'destructive' : 'outline'}
								class="rounded px-1.5 py-0 text-xs"
								title="Wage"
							>
								{worker.wage.toFixed(3)}<MdiBitcoin />
							</Badge>
							<Badge variant="secondary" class="rounded px-1.5 py-0 text-xs" title="Net wage">
								-{tax}% → {taxedWage}<MdiBitcoin />
							</Badge>
						</div>
					</div>

					<!-- Bottom row: stats -->
					<div class="flex flex-row gap-2 align-middle text-xs text-muted-foreground sm:w-1/2">
						<Badge
							variant="outline"
							class="flex w-1/4 grow gap-1 rounded-sm font-medium text-foreground"
							title="Fidelity"><MdiHeart class="size-4" /> {worker.fidelity}%</Badge
						>

						<Badge
							variant="outline"
							class="flex w-1/4 grow gap-1 rounded-sm font-medium text-foreground"
							title="Production"
							><MdiPickaxe class="size-4" /> {worker.userData.skills.production.total}</Badge
						>

						<Badge
							variant="outline"
							class="flex w-1/4 grow rounded-sm font-medium text-foreground"
							title="Energy"
							><MdiLightningBolt class="size-4" /> {worker.userData.skills.energy.total}</Badge
						>
					</div>
				</div>
			</article>
		{/each}
	</Card.Content>
</Card.Root>
